#!/bin/sh

if pgrep chrome > /dev/null; then
  pid=$(pgrep -o chrome)
  data=`top -b -n1 -p $pid | tail -n 1`
  mem=$(echo $data | awk '{print $10}' | sed s/,/./)
else
  mem=0
fi

echo $mem
echo $mem
uptime -p | sed "s/up //"
echo chrome_mem
