#!/bin/sh

mem_size=$(free -m | grep --color=never "Mem:" | awk '{print $2}')
mem_usage=$(free -m | grep --color=never "Mem:" | awk '{print $3}')

echo $mem_size
echo $mem_usage
uptime -p | sed "s/up //"
echo memory_usage
